### ISSUE TITLE
ImportError: No module named boto.ec2

### ISSUE THREAD

**Issue by necrophcodr** [funtoo/metro#20]
Following the Quick Start Tutorial exactly in a Funtoo virtual machine, running  
    ./scripts/ezbuild.sh funtoo-current pentium4  
Causes the following to be displayed:  
    Running /root/git/metro/metro -d multi: yes target/build: funtoo-current target/subarch:     pentium4 target/version: 2013-05-03 multi/mode: stage3
    Traceback (most recent call last):
      File "/root/git/metro/metro", line 216, in <module>
        Metro().run()
      File "/root/git/metro/metro", line 82, in run
        self.setup_paths()
      File "/root/git/metro/metro", line 181, in setup_paths
        self.targets = import_module("targets")
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/root/git/metro/modules/targets/__init__.py", line 5, in <module>
        from .ec2 import Ec2Target
      File "/root/git/metro/modules/targets/ec2.py", line 4, in <module>
        import boto.ec2
    ImportError: No module named boto.ec2
    build failure

**Comment by necrophcodr** [comment]
So this is a "no-fix"?

**Comment by danielrobbins** [comment]
It was fixed in git a long time ago. It will use boto if available, but won't do a traceback if it's not there.
